steps:
  - id: Download serviceAccount.json
    name: gcr.io/cloud-builders/gsutil
    args: ["cp", "gs://$PROJECT_ID-secret/operation/serviceAccount.json", "./"]

  - id: Download dotenv
    name: gcr.io/cloud-builders/gsutil
    args: ["cp", "gs://$PROJECT_ID-secret/operation/.env", "./"]

  - id: Build docker image
    name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/$PROJECT_ID/operation:$SHORT_SHA",
        "-f",
        "./Prd.Dockerfile",
        ".",
      ]

  - id: Push docker image to GCR
    name: gcr.io/cloud-builders/docker
    args: ["push", "asia.gcr.io/$PROJECT_ID/operation:$SHORT_SHA"]

  - id: Deploy Cloud Run
    name: gcr.io/cloud-builders/gcloud
    args:
      [
        "beta",
        "run",
        "deploy",
        "operation",
        "--project",
        "${PROJECT_ID}",
        "--image",
        "asia.gcr.io/$PROJECT_ID/operation:$SHORT_SHA",
        "--platform",
        "managed",
        "--region",
        "asia-northeast1",
      ]
